Vercel deployment configuration
marcos90s/stock_api pull request #3
Opened 2024-08-28 20:37 UTC by yuri-moraes

All changes was only focused on deploy the project and DB to Vercel.

2024-08-28 21:12 UTC, yuri-moraes commented
Adicionei um readme base

2024-08-30 12:52 UTC, marcos90s requested changes
Manter user_routes sem quebras de linhas

2024-08-30 13:00 UTC, marcos90s requested changes

2024-08-30 13:00 UTC, marcos90s commented on controllers/UserController.js
Ao invés de apagar e criar um novo método igual ao update, apenas mudar o nome do método para 'editUser.

2024-08-30 13:02 UTC, marcos90s commented on controllers/UserController.js
> -      if (req.body.role && req.authenticatedUser.role === 'admin') updateData.role = req.body.role;
Verificação é necessária para um usuário comum não mudar a própria role

2024-08-30 13:03 UTC, marcos90s commented on routes/user_routes.js
Manter rotas sem as quebras de linha para melhor legibilidade

2024-08-30 13:16 UTC, yuri-moraes reviewed
Fiz a atualização do método do controller, quanto às quebras de linha, é necessário configurarmos um eslint.config

2024-08-30 13:25 UTC, marcos90s approved these changes

2024-08-30 13:25 UTC, merged